name: Build wlogout

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            meson \
            ninja-build \
            libgtk-3-dev \
            libglib2.0-dev \
            libgirepository1.0-dev \
            libgtk-layer-shell-dev \
            scdoc \
            systemd

      - name: Setup build directory with meson
        run: meson build

      - name: Build with ninja
        run: ninja -C build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: wlogout
          path: build/wlogout
